// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtJZBP2dNTzj44l8-X_Q3oPQ4wMUegR4',
    appId: '1:905494334430:android:17f9c70b65cb1585b36b4f',
    messagingSenderId: '905494334430',
    projectId: 'matgo-4c9f9',
    storageBucket: 'matgo-4c9f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNKoLTcUV2hlS2r7hYEVqArLECH8rZkWo',
    appId: '1:905494334430:ios:39b005881d51e17eb36b4f',
    messagingSenderId: '905494334430',
    projectId: 'matgo-4c9f9',
    storageBucket: 'matgo-4c9f9.firebasestorage.app',
    iosBundleId: 'com.matgoapp.matgo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD64dM2xFfR_0llssKyx4gOojB7oeMPImY',
    appId: '1:905494334430:web:9fe044c8dc1b0d62b36b4f',
    messagingSenderId: '905494334430',
    projectId: 'matgo-4c9f9',
    authDomain: 'matgo-4c9f9.firebaseapp.com',
    storageBucket: 'matgo-4c9f9.firebasestorage.app',
    measurementId: 'G-HL6S3GZ9HL',
  );

}